sheets = {
    "General": ["seasonScale", "CO2Cap", "CO2Price"],
    "Sets": [
        "Nodes",
        "OffshoreNodes",
        "Horizon",
        "Storage",
        "Technology",
        "Generators",
        "LineType",
        "StorageOfNodes",
        "DirectionalLines",
        "LineTypeOfDirectionalLines",
        "GeneratorsOfNode",
        "GeneratorsOfTechnology",
        "Coords",
        "Countries",
        "NodesOfCountry",
    ],
    "Generator": [
        "CapitalCosts",
        "FixedOMCosts",
        "VariableOMCosts",
        "FuelCosts",
        "CCSCostTSVariable",
        "Efficiency",
        "RefInitialCap",
        "ScaleFactorInitialCap",
        "InitialCapacity",
        "MaxBuiltCapacity",
        "MaxInstalledCapacity",
        "MinBuiltCapacity",
        "MaxBuiltCapacityCountry",
        "MaxInstalledCapacityCountry",
        "MinBuiltCapacityCountry",
        "RampRate",
        "GeneratorTypeAvailability",
        "CO2Content",
        "CapturedCO2Content",
        "Lifetime",
    ],
    "Node": ["ElectricAnnualDemand", "NodeLostLoadCost", "HydroGenMaxAnnualProduction"],
    "Transmission": [
        "lineEfficiency",
        "MaxBuiltCapacity",
        "Length",
        "TypeCapitalCost",
        "TypeFixedOMCost",
        "InitialCapacity",
        "MaxInstallCapacityRaw",
        "Lifetime",
    ],
    "Storage": [
        "InitialPowerCapacity",
        "PowerCapitalCost",
        "PowerFixedOMCost",
        "PowerMaxBuiltCapacity",
        "EnergyCapitalCost",
        "EnergyFixedOMCost",
        "EnergyInitialCapacity",
        "EnergyMaxBuiltCapacity",
        "EnergyMaxInstalledCapacity",
        "PowerMaxInstalledCapacity",
        "StorageInitialEnergyLevel",
        "StorageChargeEff",
        "StorageDischargeEff",
        "StoragePowToEnergy",
        "StorageBleedEfficiency",
        "Lifetime",
    ],
}

# Optional sheets: allowed to be absent from a dataset (feature-gated inputs, e.g. the
# country level for national limits on NUTS-disaggregated datasets).
optional_sheets = {
    "Sets": [
        "Countries",
        "NodesOfCountry",
    ],
    "Generator": [
        "MinBuiltCapacity",
        "MaxBuiltCapacityCountry",
        "MaxInstalledCapacityCountry",
        "MinBuiltCapacityCountry",
        "CapturedCO2Content",
    ],
}
